#!/bin/sh

TOOL=./$1

${TOOL} aead drygascon 128 opt_arm_cortex-m 16
${TOOL} aead drygascon 128 opt_arm_cortex-m 32
${TOOL} aead drygascon 128 opt_arm_cortex-m 56

${TOOL} hash drygascon 128 ref  16
${TOOL} hash drygascon 256 ref  32
${TOOL} aead drygascon 128 ref  16
${TOOL} aead drygascon 256 ref  32
${TOOL} hash drygascon 128 le32 16
${TOOL} hash drygascon 256 le32 32
${TOOL} aead drygascon 128 le32 16
${TOOL} aead drygascon 256 le32 32

${TOOL} aead drygascon 128 ref  32
${TOOL} aead drygascon 128 le32 32
${TOOL} aead drygascon 128 ref  56
${TOOL} aead drygascon 128 le32 56
