#!/bin/sh

#build ONE combination of target, implementation and algorithm

#TARGET="drygascon"
#PARAM="5"
#IMPL="ref"
#ALGOTYPE="hash"

if [ "$#" -ne 5 ]; then
    echo "Illegal number of parameters"
    echo "[aead|hash] target param impl keysize"
    exit 1
fi

ALGOTYPE=$1
TARGETBASE=$2
PARAM=$3
IMPL=$4
KSIZE=$5

TARGET=${TARGETBASE}$PARAM

BASE_FLAGS="-std=c99 -Wall -Wextra -Wshadow -fstrict-aliasing -Wstrict-aliasing -I ."
OPT_FLAGS="-O3 -msse2 -msse -march=native -maes -mtune=native -fomit-frame-pointer -fwrapv"
DBG_FLAGS="-O0 -fsanitize=address,undefined "

TOOL="gcc $BASE_FLAGS $OPT_FLAGS"
#TOOL="gcc -Wall -Wextra -march=native -mtune=native -O3 -fomit-frame-pointer -fwrapv -I ."
SRCDIR=./$TARGET
BUILDDIR=./bin

mkdir --parent $BUILDDIR

case $ALGOTYPE in
aead)
    DSTDIR=./crypto_aead/${TARGET}k${KSIZE}/${IMPL}
	SUPERCOP_C_FILE=${DSTDIR}/encrypt.c
    ;;
*)
	DSTDIR=./crypto_${ALGOTYPE}/${TARGET}/${IMPL}
    SUPERCOP_C_FILE=${DSTDIR}/${ALGOTYPE}.c
    ;;
esac
echo "build $DSTDIR"

case $TARGETBASE in
gascon)
    SUPERCOP_C_FILE=$DSTDIR/encrypt.c
    ;;
esac

OTHER_C_FILES=""
MAKEMAIN=1
case $IMPL in
ref)
    ;;
le32)
    ;;
le64)
    ;;
*)
    OTHER_C_FILES="$DSTDIR/aead-common.c $DSTDIR/drygascon.c $DSTDIR/internal-drysponge.c"
    MAKEMAIN=0
    ;;
esac

if [ $MAKEMAIN -eq 1 ]
then
    $TOOL -I $DSTDIR -DKSIZE=${KSIZE} main_${ALGOTYPE}.c ${OTHER_C_FILES} -o ${BUILDDIR}/${TARGET}k${KSIZE}_${ALGOTYPE}_${IMPL}

    rm -f ${BUILDDIR}/${TARGET}_${ALGOTYPE}_${IMPL} 
    ln -s ${TARGET}k${KSIZE}_${ALGOTYPE}_${IMPL} ${BUILDDIR}/${TARGET}_${ALGOTYPE}_${IMPL} 
fi
$TOOL -I $DSTDIR -DKSIZE=${KSIZE} genkat_${ALGOTYPE}.c ${OTHER_C_FILES} ${SUPERCOP_C_FILE} -o ${BUILDDIR}/${TARGET}k${KSIZE}_genkat_${ALGOTYPE}_${IMPL}
