#!/bin/sh

#check consistency between ref and le32 implementation of ONE combination of target and algorithm

#TARGET="drygascon5"
#ALGOTYPE="hash"

ALGOTYPE=$1
TARGETBASE=$2
PARAM=$3
IMPL=$4

TARGET=${TARGETBASE}$PARAM

OUTDIR=./kat_out/${TARGET}/${ALGOTYPE}

REF=$(ls $OUTDIR/ref)
REF=$OUTDIR/ref/$REF

LE32=$(ls $OUTDIR/le32)
LE32=$OUTDIR/le32/$LE32

diff -q $REF $LE32
if [ $? -eq 1 ]; then
    echo $OUTDIR
    diff --side-by-side $REF $LE32 | head --lines=20
fi
