#!/bin/sh

#check ONE combination of target and algorithm

#TARGET="drygascon5"
#ALGOTYPE="hash"

ALGOTYPE=$1
TARGETBASE=$2
PARAM=$3
IMPL=$4
KSIZE=$5

TARGET=${TARGETBASE}$PARAM

OUTDIR=./kat_out/${TARGET}k${KSIZE}/${ALGOTYPE}

REF=$(ls $OUTDIR/ref)
REF=$OUTDIR/ref/$REF

OPT=$(ls $OUTDIR/$IMPL)
OPT=$OUTDIR/$IMPL/$OPT

diff -q $REF $OPT
if [ $? -eq 1 ]; then
    echo $OUTDIR
    diff --side-by-side $REF $OPT | head --lines=20
fi
