#!/bin/bash

./clean


if [ -z "$1" ]
then
      py=python3
else
      py=$1
fi

echo "Using '$py' as PYTHON"

$py setup.py sdist bdist_wheel

cd dist
$py -m pip uninstall -y --verbose drysponge
whl=$(ls *.whl)
$py -m pip install --user $whl
cd ..
